name: Build Cloudstream Extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: gradle build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cloudstream-extension
        path: build/libs/*.jar
